services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_DB_URI
        fromDatabase:
          name: chat-app-db
          property:connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
